/* Модуль для приложения "Сота" */

module Cell {

  /* Интерфейс обратного вызова трубки */
  interface TubeCallback {
    /* Принять сообщение message от номера fromNum */
    long getSMS (in string fromNum, in string message);

    /* Вернуть свой номер */
    string getNum();

    long getBalance(in string tubeNumber, in string tubeBalance);
    };

  /* Интерфейс базовой станции */
  interface Station {
    /* Зарегистрировать трубку с номером phoneNum,
    для обратного вызова трубки использовать ссылку TubeCallback */
    long register (in TubeCallback objRef, in string phoneNum, in string balance);
    
    /* Отправить сообщение message от номера fromNum к номеру toNum */
    long getSMS (in string fromNum, in string toNum, in string message);

    /* Получить баланс */
    long getBalance(in string tubeNumber);
    };
};
